services:
  - type: web
    name: deepfake-detection
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGODB_URI
        sync: false
